name: fudgeflix_dw
version: '1.0'
config-version: 2

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:                            # Folder: /models/fudgeflix
    +materialized: table
    +schema: fudgeflix                   # ⬅️ target schema in ANALYTICS
    +database: analytics                 # ⬅️ target database for dbt models